### ISSUE TITLE
Enhancement of documentation

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#171]
This components are for using it with the TALL-Stack.
BUT sometimes you need to use it WITHOUT Livewire (for example if you create a "real old HTML" Login-Form like Jetstream does...)

this works also fine, but the error-Messages are not rendered, because there is no livewire-model and so no matching of the error-bag.

To avoid this problem, it is only needed to add a `wire:model="xxx"`to the component - even if you DON'T use Livewire. After adding this, the error - messages gets rendered even if it is a plain HTML-Form posting its data...

for example:
```blade
    <form method="POST" action="{{ route('register') }}" novalidate>
            @csrf
            <div class="mt-4">
                <x-input id="firstname" name="firstname" wire:model="firstname" type="text" label="{{ __('Vorname') }}" value="{{old('firstname')}}" autofocus autocomplete="vorname"/>
            </div>
   .
   .
   .
  </form>

**Comment by devajmeireles** [comment]
Hey, @vogelor ! Thanks for your report.

To be honest, I'm not convinced about documenting this because it will lead people to try to use TallStackUI out of the Livewire context, and certain components wouldn't work well, so I don't believe that some and not all are enough for this case.

I prefer to let people discover it for themselves. 

TallStackUI was designed for TALL Stack applications, where normal request flow is not used as you did. Some components will still work, but not all.

**Comment by vogelor** [comment]
No problem. It is your Project - and so your decisions ;-)
To make it clear, i will also use it ONLY with Livewire (the login is my only exception, because it is "made" by jetstream )

**Comment by devajmeireles** [comment]
> No problem. It is your Project - and so your decisions ;-) To make it clear, i will also use it ONLY with Livewire (the login is my only exception, because it is "made" by jetstream )

Although TallStackUI was created by me, I want the entire environment surrounding the project to be friendly and cooperative, so your suggestions are always welcome.

I think we can make this a "trick" that people discover for themselves, because if we document this, it will only work on certain components, not all.
