### ISSUE TITLE
[Feature Request]: add classes to the components

### ISSUE THREAD

**Issue by vogelor** [tasteui/tasteui#176]
### Suggestion Theme

if i add classes to the component - for example like this:
```blade
            <x-alert color="green" icon="check" class="mb-6" close>
                {{ __('Wir haben dir eine neue Bestätigungs-Mail zugesendet. Bitte schaue auch mal in deinem SPAM-Ordner nach, falls sie nicht bei dir ankommt.') }}
            </x-alert>
```
then the "mb-6" is not added to the html-output.
this means, i can't style the components with additional classes.

at the moment i helped myself with:

```blade
            <div class="mb-6">
            <x-alert color="green" icon="check" close>
                {{ __('Wir haben dir eine neue Bestätigungs-Mail zugesendet. Bitte schaue auch mal in deinem SPAM-Ordner nach, falls sie nicht bei dir ankommt.') }}
            </x-alert>
            </div>
```
but i think this is not the "right way"...

### Main Benefits

To style the HTML with margins and more...

**Comment by devajmeireles** [comment]
We are working out what to do about this from 2024 onwards. For now, I suggest you think of the component as a mini HTML block which should therefore be embedded in a div to control external spacing.

**Comment by devajmeireles** [comment]
After a thorough review, we have no plans for this at this time. With the release of [scoped personalization, you can do this per component.](https://tallstackui.com/docs/personalization/soft#scoped-personalization)

It's difficult to think about something like this because we can't define exactly where the ideal position will be for the attributes to be added.
