### ISSUE TITLE
[Bug]: Modal closing when a Dialog is canceled

### ISSUE THREAD

**Issue by arturafonsoaa** [tasteui/tasteui#195]
### What Happened

I have a "Form Modal" with a Delete button inside. When the delete button is clicked, a Dialog is opened to confirm the action by the user. When the user clicks on the cancel button, the Diolog and the Modal are closed. What is expected is that only the dialogue will be closed.

### How to Reproduce

Just reproduce the description above

### Laravel Version

10.39.0

### Livewire Version

3.3.3

### TallStackUI Version

1.6.7

### PHP Version

8.2.12

### Operation System

Linux

**Comment by devajmeireles** [comment]
Hey, @arturafonsoaa ! Thanks for your report.

This is not a bug. This is expected behavior. When you click on cancel in Dialog, the modal understands that there was a click outside, so the modal is closed. To prevent this situation you must make the modal "persistent". See this documentation: https://tallstackui.com/docs/ui/modal#persistent. As a result of this, the modal will not close until there is a click on an element (button) that serves to close the modal.

If you still understand that this is a problem, please tag me in the answer using @
