### ISSUE TITLE
[Bug]: tallstackui script and style are not loading in prod

### ISSUE THREAD

**Issue by adamako** [tasteui/tasteui#233]
### What Happened

In local environment there is no problem with tallstackui but after deployment script and style are not found.

<img width="1672" alt="image" src="https://github.com/tallstackui/tallstackui/assets/40002929/f033244e-76a8-4195-b637-777e5d07b985">

I have already did `npm run build` and send to the server

### How to Reproduce

Deploy in production with php deployer and nginx

### Laravel Version

10.35.0

### Livewire Version

3.0.10

### TallStackUI Version

1.3.4

### PHP Version

8.2

### Operation System

Linux

**Comment by devajmeireles** [comment]
If this were a bug, our documents wouldn't work. The problem is possibly linked to cache.

First of all, **update your dependencies, because I noticed that you are using an old version of TallStackUI. In the issue you said to use version 1.3.4, while we are on version 1.9.2.**

Then put this into your production pipeline:

```shell
npm run build
php artisan optimize:clear
```

Another good thing to do is something similar to this:

```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\URL;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        //
    }

    public function boot(): void
    {
        if ($this->app->isProduction()) {
            URL::forceScheme('https');
        }
    }
}
```

**Comment by devajmeireles** [comment]
@adamako , If after following the recommendations above, you still with problems just reply here. Feel invited to join us on Discord server: https://discord.gg/sfr66WXh4A
