### ISSUE TITLE
[Bug]:  Error with the select.styled

### ISSUE THREAD

**Issue by AndreKendeck** [tasteui/tasteui#247]
### What Happened

![image](https://github.com/tallstackui/tallstackui/assets/41024720/ebe55a9e-3e5b-4bf0-83fa-442b00dc1a79)

### How to Reproduce

Upgrade to version 1.11.1

### Laravel Version

10.40.0

### Livewire Version

3

### TallStackUI Version

v1.11.1

### PHP Version

8.2.8

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey! @AndreKendeck,

This problem was resolved in some versions before the most current one. Make sure to update your Composer dependencies with the command: `composer update`.

In your case, I noticed that you published the Blade files, so you will need to update them to the latest version.

As we are an active community, we have updates almost daily, so it's good to always stay tuned. We have a Discord server that you can join to receive updates on new releases: https://discord.gg/sfr66WXh4A
