### ISSUE TITLE
Color spinner default

### ISSUE THREAD

**Issue by felipeArnold** [tasteui/tasteui#269]
### Suggestion Theme

![image](https://github.com/tallstackui/tallstackui/assets/44820260/376927b3-4f83-4de0-b0dd-35e3fc68b0ce)
![image](https://github.com/tallstackui/tallstackui/assets/44820260/57722740-6cb6-40c2-ad85-7ddfee862a3a)

### Main Benefits

Create configuration for default loading loading, as the component is based on the bg-primary-500 color, perhaps the suggestion would be to put a more standard color, for example a "slate" or create a configuration, without depending on the tailwind file.

Using the primary color, the loading is more eye-catching than the notification.

**Comment by devajmeireles** [comment]
Hey, @felipeArnold !

Since I created TallStackUI I have received a lot of questions about why certain components do not have certain configurable things (thinking about the settings in the `config.php` file), but the thing is that I believe that certain settings will not change during the life of a project, I mean, after the project is alive and in production.

For example: we don't have a configuration that makes the inputs round instead of the original style, this is because I believe that the UI of an application will never undergo a drastic change that deserves configurations like this, that is: no one will change the input style just in one environment and not another.

---

To apply changes like the one you suggested:

A) You can use soft personalization and tap the color you want, making any substitutions you want:

```php
namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use TallStackUi\Facades\TallStackUi;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        // ...

        TallStackUi::personalize()
            ->toast()
            ->block('progress.bar')
            ->replace('bg-primary-500', 'bg-red-500');
    }
}
```

Result:
![CleanShot 2024-01-29 at 12 08 23](https://github.com/tallstackui/tallstackui/assets/60591772/38733f6d-6c5b-4b06-888c-c45d633eaccd)

---

B) You can also create and apply custom colors:

In the `tailwind.config.js`:

```js
    // ...
    theme: {
        extend: {
            fontFamily: {
                sans: ['Figtree', ...defaultTheme.fontFamily.sans],
            },
            colors: {
                'custom': {
                    '50': '#ffffe4',
                    '100': '#fdffc4',
                    '200': '#faff90',
                    '300': '#f1ff50',
                    '400': '#e1ff00',
                    '500': '#c5e600',
                    '600': '#99b800',
                    '700': '#738b00',
                    '800': '#5b6d07',
                    '900': '#4c5c0b',
                    '950': '#283400',
                },
            }
        },
    },
```

The `AppServiceProvider`:

```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use TallStackUi\Facades\TallStackUi;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     */
    public function boot(): void
    {
        // ...

        TallStackUi::personalize()
            ->toast()
            ->block('progress.bar')
            ->replace('bg-primary-500', 'bg-custom-500');
    }
}
```

Result:
![CleanShot 2024-01-29 at 12 10 27](https://github.com/tallstackui/tallstackui/assets/60591772/694c88bb-c47f-47cf-a64d-eee540ea6492)


You will always be dependent on making adjustments to the Tailwind file because that is where the Tailwind settings live.

I'll close this issue, but feel free to open a new one if you have any other questions or suggestions. Thanks!
