### ISSUE TITLE
[Bug]: Button / Loading

### ISSUE THREAD

**Issue by joelhmetz** [tasteui/tasteui#284]
### What Happened

When using the button component with loading, it has the loading icon directly active, it does not just involve the click action.
The same happens with the loading component.

### How to Reproduce

To reproduce the error: I created a Laravel installation from scratch, with Breeze. I took care of creating the component within Livewire as well.

### Laravel Version

10.43.0

### Livewire Version

3.4.4

### TallStackUI Version

1.14.2

### PHP Version

8.2

### Operation System

Windows

### Notes

I noticed the error in a project after one of the most recent updates.

**Comment by devajmeireles** [comment]
Hey, @joelhmetz ! Thank you for your report. Other people reported the same issue to me, but I was unable to reproduce it. Now I finally was able to understand and reproduce the issue.

The issue happens because: 1) You are using the buttons with `loading` outside of Livewire components and/or 2) You have not loaded `@livewireStyles` in your layout header.

I just released a new version now so that `loading` will only be applied when it is inside Livewire components, but it is also necessary to add `@livewireStyles` in your layout header 👈🏻  Make sure to do that.

**I will update the doc now.**
