### ISSUE TITLE
[Bug]: Unable to locate a class or view for component [tallstack-ui::icon.solid.o-bars-3]

### ISSUE THREAD

**Issue by pboese** [tasteui/tasteui#292]
### What Happened

There seems to be some issue with all heroicons on all my environments since running `composer upgrade`

```
InvalidArgumentException

Unable to locate a class or view for component [tallstack-ui::icon.solid.o-bars-3]
```

Any ideas, what might cause this? Already ran `optimize:clear`. It doesn't matter what icon I use.

### How to Reproduce

I'm not entirely sure tbh... sorry

### Laravel Version

10.43.0

### Livewire Version

3.4.4

### TallStackUI Version

v1.14.3

### PHP Version

8.3.2

### Operation System

macOS

**Comment by hitaloramon** [comment]
Hi @pboese, 

From what I can tell, you are trying to look for an icon called ```o-bars-3``` and the correct one for heroicons would be ```bars-3```. I don't think we use this icon anywhere on TallStackUI, so it's probably an icon you're trying to insert. Check your code to see if you are passing the correct name to the icon.

**Comment by devajmeireles** [comment]
@pboese ,

Make sure you use the correct icon name, because `o-bars-3` does not exist in the Heroicons library. A good thing to do is to check the icon via the Heroicons website https://heroicons.com/

Furthermore, we are preparing a summer release 🏖️  and with that, we will add support for the other 4 icon libraries, one of them with more than 10K icons.

I'll mark this issue as resolved. Feel free to open a new one whenever necessary.
