### ISSUE TITLE
[Bug]: Alpine x-tooltip directive conflicts with FilamentPHP

### ISSUE THREAD

**Issue by corentinbtmps** [tasteui/tasteui#349]
### What Happened

As you can see from the screenshot below, the Alpine "x-tooltip" directive is already in use by FilamentPHP, so tooltips on Filament arrays are no longer functional.

Is it possible to rename this directive so that it doesn't conflict with this one? Or make it less generic?

Thank you very much for your work and this great bank of components.

<img width="1162" alt="Capture d’écran 2024-03-12 à 17 39 41" src="https://github.com/tallstackui/tallstackui/assets/77066685/86c74811-4ac7-4733-81b6-cebca7d86b97">

### How to Reproduce

Install a simple FilamentPHP table with edit buttons and include TallStackUI scripts.

### Laravel Version

10.43

### Livewire Version

3.4.4

### TallStackUI Version

1.15.5

### PHP Version

8.2

### Operation System

macOS

**Comment by devajmeireles** [comment]
Hey, @corentinbtmps ! Thanks for your report.

I've never seen you here before. I hope you're a new guy to TallStackUI, welcome! 🥳 

Sorry, but I don't feel excited to review this because I consider that Filament and TallStackUI are different things and that they should not be used together. Although it is possible to use them together, there will be several errors in addition to this. [We have a FAQ](https://tallstackui.com/docs/faq#why-use-tallstackui-instead-of-something-like-filamentphp) where we answer the question: "Why use TallStackUI instead of something like FilamentPHP?"

**Comment by corentinbtmps** [comment]
I suspected this answer and fully understand your point of view. I'm going to manage differently. Thank you for this quick response.

Yes, we are actually testing the package on our next websites, we are carefully following the news 😉

++

**Comment by renan-eduardo-pereira** [comment]
Hello @corentinbtmps,

How did you solve this problem?

**Comment by corentinbtmps** [comment]
I just don't use TallStackUI on those blade views to avoid conflicts. Filament is only used on my admin panel 😅 @renan-eduardo-pereira
