### ISSUE TITLE
[Bug]: cannot set value of select

### ISSUE THREAD

**Issue by fjeansson** [tasteui/tasteui#352]
### What Happened

**In a regular Laravel template this select is set to 3.**
<x-select.styled :options="[1,2,3]" value="3" />

**In a livewire component rendered on a regular laravel template this is not set to 3**
<x-select.styled :options="[1,2,3]" value="3" />

### How to Reproduce

Try the simple example above.

### Laravel Version

v10.48.2

### Livewire Version

v3.4.8

### TallStackUI Version

v1.20.0

### PHP Version

8.1

### Operation System

Linux

**Comment by devajmeireles** [comment]
Hey, @fjeansson !

There is a slight difference between when you use TallStackUI components inside Livewire components and when you use them out.

When using out of Livewire components, you must use `name` and `value`

```blade
<x-select.styled :options="[1,2,3]" name="options" value="3" />
```
- `name` will be used for request submit purposes
- `value` will be used to set the value, like a normal HTML input.

By the Livewire logic, when using the TallStackUI inside Livewire components you must use `wire:model` to make the bind with some Livewire public property:

```blade
<x-select.styled :options="[1,2,3]" wire:model="options" />
```

I haven't documented this, and I don't think I ever will, because **I assume people who already know about Livewire know this.**
