### ISSUE TITLE
Unable to locate a class or view for component [ts-rating].[Bug]: 

### ISSUE THREAD

**Issue by elsoftpy** [tasteui/tasteui#451]
### What Happened

When I try to use the new rating component I get the error Unable to locate a class or view for component [ts-rating]. I have a prefix configure in my .env file ```TALLSTACKUI_PREFIX=ts-```

### How to Reproduce

Previous version 1.24.5.
Upgraded with ```composer upgrade tallstackui/tallstackui``` and I got the error
Tried with ```composer update tallstackui/tallstackui``` still no luck

my blade file looks like this:
```<x-ts-rating :rate="3" />```

### Laravel Version

10.47.0

### Livewire Version

3.4.9

### TallStackUI Version

1.25.1

### PHP Version

8.3.3

### Operation System

Windows

**Comment by devajmeireles** [comment]
This is happening because you published the configuration file before an update that introduced a new component. You need to republish your configuration file:

1. Delete the current config file
2. Run `php artisan vendor:publish --tag=tallstackui.config`

https://tallstackui.com/docs/troubleshooting#non-existent-component

**Comment by elsoftpy** [comment]
Thanks! it's working now
