### ISSUE TITLE
[Bug]:  Select slow

### ISSUE THREAD

**Issue by joelhmetz** [tasteui/tasteui#471]
### What Happened

I would like to list only the first 10 records in the select, the rest would be visible when using the search within the component, any suggestions guys? I noticed that with more registration the component becomes slower to use. I am loading 700 records.

### How to Reproduce

Livewire model:
```
$this->customers = Customer::select('id', 'name', 'alias', 'document_company')->orderBy('name', 'asc')->get()
            ->map(fn (Customer $customer) => [
                'id' => $customer->id,
                'name' => $customer->name,
                'description' => "$customer->alias - $customer->document_company",
            ]);
```
Blade:
```
<div class="col-span-6">
                                <x-select.styled :options="$customers" select="label:name|value:id"
                                    wire:model="customer_id" label="Cliente *" searchable />
                            </div>
```

### Laravel Version

11.7.0

### Livewire Version

3.4.9

### TallStackUI Version

1.26.1

### PHP Version

8.2

### Operation System

Windows

**Comment by devajmeireles** [comment]
Today you have 700, tomorrow it could be 2000 or more. IMO, the best thing to do is to transform the select into an API search. Our select for now does not handle a "lazy" mode to display every 10, for example. But do you agree that it would still be a lot of records? That's why it's best to transform it into a search via API. 

I'll close this for now. Please feel free to open a new issue whenever you'd like.
