### ISSUE TITLE
Numbering row in table

### ISSUE THREAD

**Issue by wellyrm** [tasteui/tasteui#501]
in normal table with pagination, i usually do numbering like this: 

```
@foreach($rows as $i => $row)
    <tr>
        <td>{{ $rows->firstItem() + $i }}</td>
        other column
    </tr>
@endforeach
```

already trying direct call $rows inside interact, but no luck.
```
    <x-ts-table :$headers :$rows paginate>
        @interact('column_id', $row)
            {{ $rows->firstItem() }}
        @endinteract
    </x-ts-table>
```
it's result undefined variable $rows.

How to achieve this in tallstackui table?

**Comment by devajmeireles** [comment]
@wellyrm ,

You're defining `$row` and using `$rows`, that's why the reason for the error.

![CleanShot 2024-06-12 at 09 53 15](https://github.com/tallstackui/tallstackui/assets/60591772/5ae19e4e-9ede-4981-9cc1-6ec9b110a460)

**Comment by dhelazt** [comment]
I tried to do the same thing for id column, so instead of use row id as the value, i want to change it into row number like 1,2,3,4,5,6...
Because it look weird if somebody delete a row, then column id will show something like 1,2,4,6...

Because i can't access $loop inside interact :
```
@interact('column_number',$row)
     {{ $loop->index }}
@endinteract
```
the result is undefined $loop, any suggestion with this ?
Thanks
