### ISSUE TITLE
[Bug]: Select Styled component bugged

### ISSUE THREAD

**Issue by AndreKendeck** [tasteui/tasteui#549]
### What Happened

When using the select.styled component

https://github.com/tallstackui/tallstackui/assets/41024720/31774c19-0018-49c0-a8d2-8ba00ba5a0bd

### Component

Select Styled

### How to Reproduce

Click on the dropdown component, a searchable component tends to break the view or display

### Laravel Version

10.33

### Livewire Version

3.4

### TallStackUI Version

1.32

### PHP Version

8.2

### Operation System

macOS

**Comment by devajmeireles** [comment]
Thanks for reporting, @AndreKendeck !

Firstly, I was unable to reproduce this same problem in my tests:

1. Docs works well
2. All 4 of my apps that use TallStackUI work fine

At first, I suspect that you have changed the component or this problem is related to your browser. 

Which browser are you using?

**Comment by devajmeireles** [comment]
Closed due inactivity.

**Comment by AndreKendeck** [comment]
@devajmeireles when i add 

```css
/* Apply transitions to all elements */
* {
    transition: all 0.3s ease;
}
```

to my app.css file thats the reason however it was not an issue before.
