### ISSUE TITLE
[Feature Request]: Datetime picker

### ISSUE THREAD

**Issue by Alph44rchitect** [tasteui/tasteui#564]
### Suggestion Theme

We need a datetime picker for selecting a complete timestamp (`YYYY-MM-DD HH:MM:SS`) like the native datetime picker `<input type="datetime" />` does.

### Main Benefits

A beautiful input component for selecting datetimes or timestamps.

**Comment by devajmeireles** [comment]
Thanks for your request. I've talked a lot about this to other people. My honest opinion about this is that a component that combines date and time becomes difficult to manage because we will have several parameters to control the date and time, individually. For this reason, I have no plans to create this. My recommendation is to use separate components and join the date with time manually.
