### ISSUE TITLE
[Bug]: Modal

### ISSUE THREAD

**Issue by wilianmaique** [tasteui/tasteui#585]
### What Happened

Se você utilizar o exemplo da documentação o modal não abre.

```blade
<x-modal id="modal-id">
    TallStackUi
</x-modal>
 
<x-button x-on:click="$modalOpen('modal-id')">
    Open
</x-button>
``` 

mas por algum motivo se você adicionar ao button, ele começa a funcionar...

```blade
x-data=""
``` 

### Component

Modal

### How to Reproduce

..

### Laravel Version

11

### Livewire Version

3

### TallStackUI Version

last

### PHP Version

8.3

### Operation System

Windows

**Comment by devajmeireles** [comment]
Thanks for reporting! I couldn't reproduce it. What could happen is that you don't have AlpineJS on the page? In my tests, the modal opens successfully when copying the code below. The only difference between my code and yours is that in mine I am using the `ts-` prefix in the components:

```blade
<x-ts-modal id="modal-id">
    TallStackUi
</x-ts-modal>
 
<x-ts-button x-on:click="$modalOpen('modal-id')">
    Open
</x-ts-button>
```

If you understand that this is indeed a bug, I ask that you open a new issue now with a public repository that reproduces the problem, this will help us find the source of the cause and also fix it.

**Comment by wilianmaique** [comment]
o bug acontece, aconteceu comigo e mais um que testou tambem, foi testado em uma instalação limpa, sem brezze etc, somente laravel, tailwindcss livewire etc mas não funcionou

**Comment by devajmeireles** [comment]
> o bug acontece, aconteceu comigo e mais um que testou tambem, foi testado em uma instalação limpa, sem brezze etc, somente laravel, tailwindcss livewire etc mas não funcionou

Considering it still happens to you and others, a likely reason would be that there are no Livewire components on the page. [As we mentioned in our docs](https://tallstackui.com/docs/installation#alpinejs-requirement), **Livewire 3 only injects AlpineJS into the page if there is a Livewire component in the page.**

If you try to copy some examples from our docs and use it on a page in a new Laravel application, such as `dashboard.blade.php` without AlpineJS being loaded, it really won't work, due to Livewire's behavior policy in its new version . [The solution for this is described here!](https://tallstackui.com/docs/installation#alpinejs-requirement)

**If you are loading AlpineJS as directed and it still doesn't work**, I would need to analyze the code, so you will need to send an example of a public repository with the code generating the error.

**Comment by devajmeireles** [comment]
By the way, I'm not disregarding your report, but if this were a bug I would have already received several reports from other users, including my own experience using it. I currently have 4 projects in production using TallStackUI, with Laravel, Livewire, and AlpineJS in the latest version.

**Comment by wilianmaique** [comment]
todos os outros componentes funciona, mas o modal não inicia se não colocar  x-data="", esse modal é iniciado pelo alpinejs e n pelo wire

```blade
<x-modal id="modal-id">
    TallStackUi
</x-modal>
 
<x-button x-data="" x-on:click="$modalOpen('modal-id')">
    Open
</x-button>
```
