### ISSUE TITLE
[Bug]: Identifier 'Ft' has already been declared

### ISSUE THREAD

**Issue by marpesha** [tasteui/tasteui#717]
### What Happened

I have a layout where components are rendered using Livewire and have followed the TallStackUI documentation for integration. The issue occurs consistently when navigating to a new page using livewire:navigate. I put     <tallstackui:script /> before vite once in layouts.app
 

### Component

None (N/A)

### How to Reproduce

when I click                     
x-button color="secondary"  href="{{route('partner.profile.show')}}" wire:navigate>{{__('Dashboard')}}/x-button
appears error 
Uncaught SyntaxError: Identifier 'Ft' has already been declared (at tallstackui-BHc8UZAH.js:1:1)

### Laravel Version

10.10

### Livewire Version

3.5

### TallStackUI Version

1.35

### PHP Version

8.1

### Operation System

Windows

### Notes

Maybe this is my fail

**Comment by devajmeireles** [comment]
Hello! @marpesha! First of all, sorry for replying late. I was fully focused on moving to the new office. In order to understand and help you with this issue, I need to understand more about your environment and the components you are using. Can you share the project with me or create a public repository where I can reproduce this issue? I currently have two applications in production using Livewire 3 with SPA effect and I don't see this same issue in my applications, that's why I am asking you to help me reproduce this issue.

**Comment by marpesha** [comment]
Hello, after a long time, I resolved the problem. What I did:

Updated to Laravel 11 from 10
Also updated all dependencies
Upon further investigation, I noticed that several components were not Livewire, which caused errors throughout the project. After replacing them with Livewire components, everything started working.

**Comment by branivreyes** [comment]
I just want to mention that I also had this problem and it was some kind of code collision with a fontawesome kit script (https://kit.fontawesome.com). The error was: `Uncaught SyntaxError: Identifier 'Bt' has already been declared (at tallstackui-BXHWXOEC.js:1:1)`. So, I don't know which is the one doing something wrong.
