### ISSUE TITLE
Date and Time Pickers Missing

### ISSUE THREAD

**Issue by mai1237** [tasteui/tasteui#93]
Very good work
It would be nice if there were
DatePicker
TimePicker
and DateTimePicker

**Comment by devajmeireles** [comment]
Hey, @mai1237 ! Thank you for your report!

To be extremely honest with you, we are planning what exactly to do about these components because we don't have them yet.

In my mind, I have a certain concern about creating a component like a date picker because even though we do a great job on it, we still won't be able to achieve all the objectives of a date picker, such as date range, disable date range, select only specific dates, select multiple dates and things like that.

As I'm a perfectionist, it won't be good if I do the simple thing 😂  

We will definitely have a solution, but I don't know what it is yet.

**Comment by devajmeireles** [comment]
@mai1237 ,

I've tagged this issue as a feature request, so we will work on this soon. 

According to our policy, I'll close this issue. Feel free to open a new issue whenever necessary.
