### ISSUE TITLE
[Feature Request]: Chat Bubble

### ISSUE THREAD

**Issue by andrefelipe18** [tasteui/tasteui#98]
### Suggestion Theme

Data display

### Main Benefits

I would like to propose the addition of chat bubbles as a feature in the library. Chat bubbles are a visual representation commonly used in messaging applications to display individual messages within a conversation. This feature can enhance the user experience and make the library more versatile for various chat-based applications.

UI has never been my strength. I've created these small examples of chat bubbles, bubbles with header and footer text, bubbles with avatars, and colored bubbles.
![Screenshot_17](https://github.com/tallstackui/tallstackui/assets/96439642/6cd8fa73-4a03-4184-b22f-27fa4d2aefe0)
![Screenshot_18](https://github.com/tallstackui/tallstackui/assets/96439642/e18a4b9e-d1f4-4cde-b1dd-604dfa7c913c)
![Screenshot_19](https://github.com/tallstackui/tallstackui/assets/96439642/91f44a2a-1804-4045-bb64-e1b65e810b0a)
![Screenshot_20](https://github.com/tallstackui/tallstackui/assets/96439642/43e46ba5-f078-494a-a902-8af909396a09)

### Source of the Suggestion

https://daisyui.com/components/chat/

**Comment by devajmeireles** [comment]
Hey, @andrefelipe18 ! Thank you for your feature request. This is awesome!

We need to keep in mind the main goal of TallStackUI: to provide useful components for interacting with Livewire. I can't see many benefits of integration between Livewire and a chat bubble component, so I think it will be only a TailwindCSS component, that will be used in a chat.

According to that, I'll move this feature request to our backlog because we are prioritizing the creation of any component that is useful to be used with Livewire at this moment.
